name: Health Check

on:
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check app health
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-uvak.onrender.com/health
          max-attempts: 3
          retry-delay: 30s
          retry-all: true